internal/core/openapi/openapi.go
internal/core/plugin/chain.go
internal/core/plugin/chain_test.go
internal/core/plugin/logging/logging.go
internal/core/plugin/permission/permission.go
internal/core/plugin/response/response.go
internal/pkg/context/context.go
internal/pkg/executor/chain.go
internal/pkg/executor/executor.go

add context field.

---

internal/core/exchanger/etcd/etcd.go
internal/core/exchanger/etcd/etcd_test.go
internal/envcd/envcd.go
internal/envcd/envcd_test.go

[type:fix] fix etcd config param

---

internal/pkg/constants/constants.go

[type:fix] fix plugin order

---

internal/core/plugin/logging/logging.go
internal/core/plugin/logging/logging_test.go

[type:refactor] refactor log

---

config/envcd.yaml
internal/core/exchanger/etcd/etcd.go
internal/core/exchanger/etcd/etcd_test.go
internal/core/exchanger/exchange.go
internal/core/exchanger/exchange_test.go
internal/core/storage/storage.go
internal/envcd/envcd.go
internal/pkg/config/config.go
internal/pkg/config/config_test.go
internal/pkg/config/conn_metadata.go
internal/pkg/config/conn_metadata_test.go

[type: refactor] refactor config.

---

config/envcd.yaml
internal/core/exchanger/exchange.go
internal/core/openapi/openapi.go

[type: bug] fix exchanger bug.

---

internal/core/exchanger/exchange.go
internal/core/exchanger/exchange_test.go

[type: refactor] optimize interface value check logic.

---

internal/core/exchanger/etcd/etcd.go
internal/core/exchanger/etcd/etcd_test.go
internal/core/exchanger/exchange_test.go
internal/core/plugin/chain_test.go
internal/pkg/config/config_test.go

[type: test] cover test

---

db/envcd.sql

[type: refactor] refactor db script.

---

db/envcd.sql

chore: modify sql

---

db/envcd.sql

Revert "chore: modify sql"

---

internal/core/openapi/auth.go
internal/core/openapi/dictionary.go
internal/core/openapi/openapi.go

[type:feat] add openapi

---

internal/core/openapi/auth.go
internal/core/storage/dao/dao.go
internal/core/storage/dao/user_proxy.go
internal/core/storage/storage.go

[type: refactor] refactor dao & storage.

---

internal/core/storage/storage.go

[type: refactor] refactor read xml

---

internal/core/openapi/auth.go
internal/util/contextutil.go

[type:feat] build context

---

internal/core/openapi/auth.go
internal/core/openapi/context.go

[type: refactor] refactor envcd context build.

---

internal/core/openapi/openapi.go
internal/util/passwordutil.go
internal/util/passwordutil_test.go

feat：password generate strategy submit

[type:feat] password generate strategy submit

---

internal/core/openapi/dictionary.go
internal/core/openapi/openapi.go

[type:refactor] refactor openapi and dictionary

---

.github/workflows/license.yaml
.licenserc.json
internal/core/exchanger/etcd/etcd_test.go

[type: feat] add file license check

---

internal/core/openapi/password.go
internal/core/openapi/password_test.go

[type: refactor] refactor password logic.

---

go.mod
go.sum
internal/core/jwt/authjwt.go
internal/core/openapi/user.go

[type:feat] user login.

---

internal/core/openapi/application.go
internal/core/openapi/context.go
internal/core/openapi/dictionary.go
internal/core/openapi/openapi.go
internal/core/openapi/user.go
internal/core/plugin/chain.go
internal/core/plugin/chain_test.go
internal/core/plugin/logging/logging.go
internal/core/plugin/logging/logging_test.go
internal/core/plugin/permission/permission.go
internal/pkg/context/context.go
internal/pkg/executor/chain.go
internal/pkg/executor/executor.go
pkg/entity/result/envcd_result.go
pkg/entity/result/envcd_result_test.go

[type: refactor] refactor context & envcd result

---

internal/core/openapi/application.go
internal/core/openapi/context.go
internal/core/openapi/dictionary.go
internal/core/openapi/openapi.go
internal/core/openapi/user.go
internal/pkg/context/context.go
pkg/entity/result/envcd_result.go
pkg/entity/result/envcd_result_test.go

[type: refactor] refactor build context.

---

internal/core/openapi/application.go
internal/core/openapi/context.go
internal/core/openapi/dictionary.go
internal/core/openapi/openapi.go
internal/core/openapi/user.go

[type: refactor] refactor openapi and dictionary.

---

db/envcd.sql
internal/core/openapi/dictionary.go
internal/core/openapi/openapi.go
internal/core/openapi/scopespace.go
internal/core/openapi/user.go

[type: refactor] refactor openapi router group

---

internal/core/openapi/dictionary.go
internal/core/openapi/openapi.go
internal/core/openapi/scopespace.go
internal/core/openapi/user.go
internal/core/plugin/permission/permission.go
internal/pkg/context/context.go

[type: refactor] refactor permission action & add gin custom recovery.

---

internal/core/openapi/user.go

[type:feat] get user & get users

---

internal/core/openapi/dictionary.go
internal/core/plugin/logging/logging.go
internal/core/plugin/permission/permission.go
internal/pkg/plugin/sort.go
pkg/entity/result/envcd_result.go
pkg/entity/result/evncd_errors.go

[type: refactor] refactor errors

---

README.md
internal/core/openapi/dictionary.go
internal/core/openapi/openapi.go
internal/core/openapi/user.go
internal/core/plugin/chain.go
internal/core/plugin/chain_test.go
pkg/entity/result/envcd_result.go
pkg/entity/result/envcd_result_test.go
pkg/entity/result/evncd_errors.go

[type: refactor] refactor the envcd errors.

---

internal/core/openapi/dictionary.go
internal/pkg/constant/constants.go
pkg/entity/result/evncd_errors.go

[type:feat] add dictionary

---

internal/core/openapi/dictionary.go
internal/core/openapi/scopespace.go

[type:feat] add scopespace

---

db/envcd.sql
internal/core/storage/xml/dictionary_mapper.xml
internal/pkg/entity/dictionary.go

[type:fix] fix sql script

---

internal/core/openapi/user.go
internal/core/storage/dao/dictionary.go
internal/core/storage/dao/permission.go
internal/core/storage/dao/user.go
internal/core/storage/xml/dictionary_mapper.xml
internal/core/storage/xml/permission_mapper.xml
internal/core/storage/xml/user_mapper.xml

[type:feat] add delete user api

---

internal/core/storage/dao/dictionary.go
internal/core/storage/dao/scopespace.go
internal/core/storage/xml/dictionary_mapper.xml
internal/core/storage/xml/scopespace_mapper.xml

[type:fix] add batch delete and update

---

internal/core/openapi/openapi.go

update uri query params

---

go.mod
go.sum
internal/core/openapi/dictionary.go
internal/core/openapi/scopespace.go
internal/core/storage/dao/dictionary.go
internal/core/storage/storage.go
internal/pkg/entity/dictionary.go

[type:fix] fix dictionary

---

go.mod
go.sum
internal/core/openapi/dictionary.go
internal/core/openapi/openapi.go
internal/core/openapi/password.go
internal/core/openapi/scopespace.go
internal/core/openapi/user.go

[type: refactor] refactor dictionary and user logic.

---

internal/core/openapi/dictionary.go
internal/core/storage/xml/scopespace_mapper.xml
internal/pkg/entity/scopespace.go

[type:fix] fix db

---

db/envcd.sql
go.mod
internal/core/openapi/user.go
internal/core/storage/dao/dictionary.go
internal/core/storage/dao/permission.go
internal/core/storage/xml/dictionary_mapper.xml
internal/core/storage/xml/permission_mapper.xml
internal/core/storage/xml/scopespace_mapper.xml
internal/pkg/entity/scopespace.go

[type:feat] refactor remove user function

---

internal/core/openapi/context.go
internal/core/openapi/token.go
internal/core/openapi/user.go
internal/pkg/context/context.go

[type: refactor] refactor the token parser and validate logic.
